server:
  port: 10015
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    enabled: true
    cache: false
    mode: HTML5
    servlet:
      content-type: text/html
svg:
  dir: file:C:/svg/